# Generated by Django 5.2.8 on 2025-11-22 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email for follow-up", max_length=254)),
                ('symptoms', models.TextField(help_text="User's described symptoms")),
                ('clinical_history_file', models.FileField(blank=True, help_text='Uploaded clinical history document', null=True, upload_to='clinical_history/')),
                ('additional_context', models.TextField(blank=True, help_text='Additional context provided by user', null=True)),
                ('category', models.CharField(help_text='AI-detected category (anxiety, depression, etc.)', max_length=50)),
                ('urgency', models.CharField(help_text='Urgency level (low, medium, high, crisis)', max_length=20)),
                ('safety_concern', models.BooleanField(default=False, help_text='Flag for self-harm or crisis situations')),
                ('triage_reasoning', models.TextField(help_text="AI's reasoning for categorization")),
                ('full_text_content', models.TextField(help_text='Complete submission formatted as coherent text')),
                ('ai_deep_analysis', models.TextField(help_text='Comprehensive AI analysis of the submission')),
                ('recommended_specialist_type', models.CharField(blank=True, help_text='Type of specialist recommended (e.g., CBT therapist, psychiatrist)', max_length=100, null=True)),
                ('key_insights', models.JSONField(default=dict, help_text='Structured insights from AI (JSON format)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether the submission has been fully processed')),
            ],
            options={
                'verbose_name': 'Triage Submission',
                'verbose_name_plural': 'Triage Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
