# Generated by Django 5.2.8 on 2025-11-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagesubmission',
            name='additional_context',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='ai_deep_analysis',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='clinical_history_file',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='key_insights',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='recommended_specialist_type',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='safety_concern',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='triage_reasoning',
        ),
        migrations.RemoveField(
            model_name='triagesubmission',
            name='urgency',
        ),
        migrations.AlterField(
            model_name='triagesubmission',
            name='full_text_content',
            field=models.TextField(help_text='Complete submission including user data and AI analysis'),
        ),
        migrations.AlterField(
            model_name='triagesubmission',
            name='processed',
            field=models.BooleanField(default=True, help_text='Whether the submission has been processed'),
        ),
    ]
